"""Rules and configs for the edge node: a small public VPS that forwards players' traffic through a WireGuard tunnel to the machine that runs the servers.

The game machine starts the tunnel (outbound only), so it needs **no open ports** and its IP never reaches a player. The edge does DNAT only — no masquerade — so
the server sees each player's real IP (bans, logs). Replies go back through the tunnel by policy routing on the game machine and are un-NATed by the edge's
conntrack. Everything here is text to review and copy to the machines; nothing is applied from here.

- `game_ports(servers)`: the public ports to forward = each server's game port (tcp+udp, `base`) and its public HTTP port (tcp, `base+1`); never the plugin ports
  (`base+2/3`, local) or acServer's own internal HTTP.
- `nft_ruleset`: table `opr_edge` (DNAT + forward policy drop + a per-source packet-rate cap so one address cannot flood a server).
- `wg_edge` / `wg_backend`: WireGuard configs (keys are placeholders: generate them with `wg genkey` on each machine).
Provider-level DDoS mitigation is still what stops volumetric floods; this only keeps the rest orderly and the origin hidden.
"""

from __future__ import annotations

import ipaddress

from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import PlainTextResponse
from sqlmodel import select

from app.auth import require
from app.db import SessionDep
from app.models import Server

router = APIRouter(prefix="/edge", tags=["edge"], dependencies=[Depends(require("admin"))])
TABLE = 100   # routing table on the game machine for replies that must go back through the tunnel


def game_ports(servers: list[Server], ports_of) -> dict[str, list[int]]:
    """{"udp": [...], "tcp": [...]} to forward. `ports_of(base)` = servers._ports."""
    udp, tcp = set(), set()
    for s in servers:
        p = ports_of(s.base_port)
        udp.add(p["udp"])
        tcp.update((p["tcp"], p["http"]))
    return {"udp": sorted(udp), "tcp": sorted(tcp)}


def _set(ports: list[int]) -> str:
    return ", ".join(str(p) for p in ports) or "0"


def nft_ruleset(ports: dict[str, list[int]], *, public_iface: str, wg_iface: str, backend_ip: str, pps_per_source: int = 600) -> str:
    return f"""# generated by the manager (app/edge.py) — review, then: nft -f /etc/nftables.d/opr_edge.nft   (and sysctl net.ipv4.ip_forward=1)
table ip opr_edge
delete table ip opr_edge
table ip opr_edge {{
  set game_udp {{ type inet_service; elements = {{ {_set(ports['udp'])} }} }}
  set game_tcp {{ type inet_service; elements = {{ {_set(ports['tcp'])} }} }}

  chain prerouting {{
    type nat hook prerouting priority dstnat; policy accept;
    iifname "{public_iface}" udp dport @game_udp dnat to {backend_ip}      # DNAT only: the source address (the player's) is kept
    iifname "{public_iface}" tcp dport @game_tcp dnat to {backend_ip}
  }}

  chain forward {{
    type filter hook forward priority filter; policy drop;
    ct state established,related accept
    iifname "{public_iface}" oifname "{wg_iface}" ip daddr {backend_ip} udp dport @game_udp \\
      meter per_source {{ ip saddr limit rate over {pps_per_source}/second burst {pps_per_source * 2} packets }} drop      # one address cannot flood a server
    iifname "{public_iface}" oifname "{wg_iface}" ip daddr {backend_ip} udp dport @game_udp accept
    iifname "{public_iface}" oifname "{wg_iface}" ip daddr {backend_ip} tcp dport @game_tcp ct state new \\
      meter new_tcp {{ ip saddr limit rate over 30/second burst 60 packets }} drop
    iifname "{public_iface}" oifname "{wg_iface}" ip daddr {backend_ip} tcp dport @game_tcp accept
  }}
}}
"""


def wg_edge(*, edge_ip: str, backend_ip: str, listen_port: int) -> str:
    return f"""# /etc/wireguard/wg0.conf on the EDGE (public VPS)
[Interface]
Address = {edge_ip}/24
ListenPort = {listen_port}
PrivateKey = <EDGE_PRIVATE_KEY>          # wg genkey | tee edge.key | wg pubkey > edge.pub

[Peer]                                    # the game machine
PublicKey = <BACKEND_PUBLIC_KEY>
AllowedIPs = {backend_ip}/32
"""


def wg_backend(*, edge_ip: str, backend_ip: str, edge_endpoint: str, wg_iface: str = "wg0") -> str:
    return f"""# /etc/wireguard/{wg_iface}.conf on the GAME MACHINE (starts the tunnel; no port is opened in the router)
[Interface]
Address = {backend_ip}/24
PrivateKey = <BACKEND_PRIVATE_KEY>
Table = off                               # do not make the tunnel the default route
PostUp = ip rule add from {backend_ip} table {TABLE}; ip route add default dev %i table {TABLE}; sysctl -w net.ipv4.conf.%i.rp_filter=2
PostDown = ip rule del from {backend_ip} table {TABLE}; ip route del default dev %i table {TABLE}

[Peer]                                    # the edge
PublicKey = <EDGE_PUBLIC_KEY>
Endpoint = {edge_endpoint}
AllowedIPs = 0.0.0.0/0                    # replies to any player go back through the edge (only {backend_ip}-sourced traffic is routed here, see PostUp)
PersistentKeepalive = 25
"""


def _ip(v: str, what: str) -> str:
    try:
        return str(ipaddress.ip_address(v))
    except ValueError as e:
        raise HTTPException(422, f"{what} is not an IP address") from e


@router.get("/rules", response_class=PlainTextResponse)
def rules(sess: SessionDep, kind: str = Query(pattern="^(nft|wg-edge|wg-backend)$"), backend_ip: str = "10.8.0.2", edge_ip: str = "10.8.0.1",
          public_iface: str = Query(default="eth0", pattern=r"^[a-zA-Z0-9_.-]{1,15}$"), wg_iface: str = Query(default="wg0", pattern=r"^[a-zA-Z0-9_.-]{1,15}$"),
          edge_endpoint: str = Query(default="EDGE_PUBLIC_IP:51820", pattern=r"^[A-Za-z0-9_.\-]+:\d{1,5}$"), pps: int = Query(default=600, ge=50, le=20000)) -> str:
    """The text for the edge or the game machine, from the servers this manager knows. Review it before using it."""
    from app import servers as srv   # lazy: servers imports a lot
    backend_ip, edge_ip = _ip(backend_ip, "backend_ip"), _ip(edge_ip, "edge_ip")
    if kind == "nft":
        ports = game_ports(list(sess.exec(select(Server))), srv._ports)
        return nft_ruleset(ports, public_iface=public_iface, wg_iface=wg_iface, backend_ip=backend_ip, pps_per_source=pps)
    if kind == "wg-edge":
        return wg_edge(edge_ip=edge_ip, backend_ip=backend_ip, listen_port=int(edge_endpoint.rsplit(":", 1)[1]))
    return wg_backend(edge_ip=edge_ip, backend_ip=backend_ip, edge_endpoint=edge_endpoint, wg_iface=wg_iface)
