"""docs/quality/BASELINE.md stays true (plan T0.2). Run: python ops/check_baseline.py        (python ops/check_baseline.py --write refreshes the generated table)
Checks that the table of routes SHARED with other components is exactly what the app serves, and that every file the document names exists."""
import os
import re
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOC = ROOT / "docs" / "quality" / "BASELINE.md"
os.environ.setdefault("ACM_DATA_DIR", tempfile.mkdtemp(prefix="acm-baseline-"))
sys.path.insert(0, str(ROOT))
from app.main import app  # noqa: E402

SHARED = {   # what other components call on the manager, by prefix
    "/healthz": "deploy.sh and monitoring",
    "/api/v1/telemetry/": "in-game client v0.1.0 (clients/OPRTelemetry), clients/probe.py",
    "/api/v1/servers": "the site's panels and the calendar (via OPR WP /api/admin/acm/*), the manager's own UI",
    "/api/v1/events": "the site's calendar sync (calendar_sync), the manager's UI",
    "/api/v1/schedules": "the site's calendar sync, the manager's UI",
    "/api/v1/championships": "the site (leagues), the manager's UI",
    "/api/v1/metrics": "the site's metrics panel",
}
BEGIN, END = "<!-- routes:begin (generated by ops/check_baseline.py --write) -->", "<!-- routes:end -->"


def table():
    rows = set()
    for path, ops in app.openapi()["paths"].items():   # (the OpenAPI document lists every route, wherever the routers were included)
        for prefix, who in SHARED.items():
            if path.startswith(prefix):
                rows |= {(m.upper(), path, who) for m in ops if m in ("get", "post", "put", "patch", "delete")}
                break
    out = ["| method | path | shared with |", "|---|---|---|"] + [f"| {m} | `{p}` | {w} |" for m, p, w in sorted(rows, key=lambda x: (x[2], x[1], x[0]))]
    return "\n".join(out)


def check(write=False):
    doc = DOC.read_text(encoding="utf-8")
    generated = f"{BEGIN}\n{table()}\n{END}"
    if write:
        DOC.write_text(re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), lambda m: generated, doc, flags=re.S), encoding="utf-8")
        return []
    problems = []
    m = re.search(re.escape(BEGIN) + r".*?" + re.escape(END), doc, re.S)
    if not m or m.group(0) != generated:
        problems.append("the table of shared routes is out of date: run python ops/check_baseline.py --write")
    for name in sorted(set(re.findall(r"`((?:ops|tests|docs|clients|app)/[\w./-]+\.(?:py|js|sh|md|html))`", doc))):
        if not (ROOT / name).exists():
            problems.append(f"the document names `{name}`, which does not exist")
    return problems


if __name__ == "__main__":
    bad = check("--write" in sys.argv)
    if bad:
        sys.exit("BASELINE.md is not in step with the code:\n  " + "\n  ".join(bad))
    print("baseline refreshed" if "--write" in sys.argv else "baseline ok")
